# See https://docs.aspect.build/v/workflows/config
---
workspaces:
  - .
  - docs
  - example
tasks:
  - test:
  - test:
      name: "Test (WORKSPACE)"
      bazel:
        flags:
          - --noenable_bzlmod
          - --enable_workspace
notifications:
  github: {}
